### Recuperar todas los blogs
GET http://localhost:3003/api/blogs
### Añadir un blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "MongoDB Atlas",
  "author": "MongoDb",
  "url": "https://www.mongodb.com/atlas",
  "likes": 7
}
### Nuevo registro
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "GitHub",
  "author": "Github",
  "url": "https://github.com/",
  "likes": 10
}
### Nuevo registro
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "full stack open",
  "author": "Universidad de Helsinki",
  "url": "https://fullstackopen.com/es/",
  "likes": 30
}
### Nuevo registro
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Programación",
  "author": "martin fowleer",
  "url": "https://martinfowler.com/",
  "likes": 24
}
### Nuevo registro
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Programación Joan Leon",
  "author": "Joan Leon",
  "url": "https://joanleon.dev/",
  "likes": 5
}

### Nuevo registro
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Joan Leon",
  "url": "https://joanleon.dev/",
  "likes": 5
}

### Recuperar un blog existente
GET http://localhost:3003/api/blogs/65f6b518adb1f83ee8cbc016

### Recuperar un blog con una id erronea
GET http://localhost:3003/api/blogs/a6

### Recuperar un blog con una id no existente
GET http://localhost:3003/api/blogs/55f6b518adb1f83ee8cbc016

### borrar un blog con una id
DELETE  http://localhost:3003/api/blogs/6609b6fff6f2c394a14e877e